name: CI

on: [push]

jobs:

  build-test:

    name: Unit Testing
    runs-on: ubuntu-latest

    services:

      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ secrets.DB_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306
        options: >-
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run unit tests
        uses: php-actions/phpunit@v4
        env:
          APP_KEY: ${{secrets.APP_KEY}}
          DB_CONNECTION: mysql
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        with:
          configuration: phpunit.xml
          php_extensions: "mysqli pdo_mysql"